### ISSUE TITLE
Update notifier doesn't activate automatically/manually

### ISSUE THREAD

**Issue by nh777** [mmontuori/atrix-mrom#13] opened 2012-09-26 17:48 UTC
I'm on version 915 of the rom, but after reboots and manually checking via MROM apk I still don't get a notification of an update.

--------- beginning of /dev/log/main

I/ZConnectionManager(18634): Burst notification to observing clients sent

D/dalvikvm( 2171): GC_EXPLICIT freed 175K, 45% free 3864K/6919K, external 0K/0K, paused 80ms

--------- beginning of /dev/log/system

I/ActivityManager( 1500): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mmontuori.atrix_mrom/.TestCheckin } from pid 1744

D/dalvikvm( 1744): GC_CONCURRENT freed 2064K, 45% free 5903K/10631K, external 6384K/7446K, paused 2ms+4ms

D/dalvikvm( 1744): GC_CONCURRENT freed 2213K, 47% free 5737K/10631K, external 5801K/7245K, paused 1ms+3ms

I/ActivityManager( 1500): Start proc com.mmontuori.atrix_mrom for activity com.mmontuori.atrix_mrom/.TestCheckin: pid=19973 uid=10073 gids={1015, 3003}

D/szipinf (19973): Initializing inflate state

D/dalvikvm(19973): GC_EXTERNAL_ALLOC freed 43K, 51% free 2684K/5379K, external 0K/0K, paused 25ms

I/ActivityManager( 1500): Displayed com.mmontuori.atrix_mrom/.TestCheckin: +668ms

I/MROM    (19973): Clicked

I/MROM    (13510): Checking in: http://www.montuori.net/mrom/checkin.php?ip=192.168.1.106&&build=olympus%3AMROM%3Aeng.michael.20120914.235220%3A4.5.141%3AMB860%3A2.3.7%3A10&&device_id=353648046147889

I/MROM    (13510): latest version:null

I/MROM    (13510): running version:olympus-MROM-eng.michael.20120914.235220

I/MROM    (19973): Clicked

I/MROM    (13510): Checking in: http://www.montuori.net/mrom/checkin.php?ip=192.168.1.106&&build=olympus%3AMROM%3Aeng.michael.20120914.235220%3A4.5.141%3AMB860%3A2.3.7%3A10&&device_id=353648046147889

D/dalvikvm(18993): GC_EXPLICIT freed 94K, 47% free 3503K/6599K, external 0K/512K, paused 68ms

I/MROM    (13510): latest version:null

I/MROM    (13510): running version:olympus-MROM-eng.michael.20120914.235220

**Comment by mmontuori** [comment] 2012-09-27 03:02
It is possible you have a firewall preventing to reach www.montuori.net? I ran the url http://www.montuori.net/mrom/checkin.php?ip=192.168.1.106&&build=olympus%3AMROM%3Aeng.michael.20120914.235220%3A4.5.141%3AMB860%3A2.3.7%3A10&&device_id=353648046147889 manually and got the following back:

[{"id":"4","name":"current_version","value":"olympus:MROM:eng.michael.20120925.195929"},{"id":"5","name":"debug","value":"false"}]

The new version is reported back. can you try to open the URL from your phone and see if you get the same thing back?

**Comment by nh777** [comment] 2012-09-27 03:12
I doubt it's a firewall. I tried accessing it via wifi and 3g but neither worked. 

I'll flash back to 0915 and see what happens. As of right now in 0925, I'm showing the same thing as you with that URL.

**Comment by mmontuori** [comment] 2012-09-27 03:33
I think the issue is now fixed!!! I found the problem... it should work...

**Comment by nh777** [comment] 2012-09-27 03:42
Great! I'm assuming it's with your site and not the rom version?

**Comment by mmontuori** [comment] 2012-09-27 05:11
Yes all on the site, the ROM is fine...

**Closed as completed** 2012-09-27 12:49 UTC
