### ISSUE TITLE
MmsExtra process FC when screen is lighten up by mms ONLY from China Unicom！

### ISSUE THREAD

**Issue by jlm346383101** [mmontuori/atrix-mrom#19] opened 2012-10-25 15:05 UTC
YOUR original ROM doesn't  contain the function ,which may be useful for somebody！As the title, when my phone screen's black and i receive a mms from China Unicom，(just it，other carriers or any  phonenumber no such problem)，MmsExtra process gets to force close！
maybe it's not a bug, but it happens just on my atrix 4G！

**Comment by mmontuori** [comment] 2012-10-28 01:01
Can you collect logcat and send it me it will help me in figuring out what the problem is. Also have you tried a different mms application like handcent?

**Comment by jlm346383101** [comment] 2012-10-28 01:24
I've got the logcat but didn't find the right place to upload it. It's about the mms.apk and mmsextra.apk,which i repalced as i like the Popmms! Also,I tried to install the SMS Popup.apk as attached! But I haven't tried other mms apps.

As it's the first for me to get the logcat, I'll send it all to you!
Logcat as attached!

Now I have a problem that the boot time up to 30s,and is it too long? of course I disabled items of apps i've installed!
Best of all,thanks for your rom and i like it so much!

------------------ 原始邮件 ------------------
发件人: "Michael Montuori"notifications@github.com;
发送时间: 2012年10月28日(星期天) 上午9:01
收件人: "mmontuori/atrix-mrom"atrix-mrom@noreply.github.com; 
抄送: "jlm346383101"346383101@qq.com; 
主题: Re: [atrix-mrom] MmsExtra process FC when screen is lighten up by mms ONLY from China Unicom！ (#19)

Can you collect logcat and send it me it will help me in figuring out what the problem is. Also have you tried a different mms application like handcent?

```
           —
           Reply to this email directly or view it on GitHub.
```

**Comment by mmontuori** [comment] 2012-10-29 20:28
I never got the logcat, please email it to me at michael.montuori@gmail.com

**Comment by mmontuori** [comment] 2012-11-01 19:31
This appears to be an application issue, mmsextra gets the following exception, forward this to antutu MmsExtra application developer:

10-25 22:11:10.340 E/AndroidRuntime( 2551): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.antutu.MmsExtra/com.antutu.MmsExtra.smspopup.SmsPopupActivity}: android.database.sqlite.SQLiteException: unrecognized token: "'温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】": , while compiling: SELECT _id, date, thread_id, body FROM (SELECT DISTINCT date \* 1 AS normalized_date, _id, date, thread_id, body FROM sms WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】����' AND thread_id = 1 AND (type != 3)) UNION SELECT DISTINCT date \* 1000 AS normalized_date, pdu._id, date, thread_id, NULL AS body FROM pdu LEFT JOIN pending_msgs ON pdu._id = pending_msgs.msg_id WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】����' AND thread_id = 1 AND msg_box != 3 AND (msg_box != 3 AND (m_type = 128 OR m_type = 132 OR m_type = 130))) ORDER BY date DESC) ORDER BY date DESC

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.app.ActivityThread.access$1500(ActivityThread.java:123)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.os.Handler.dispatchMessage(Handler.java:99)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.os.Looper.loop(Looper.java:130)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at android.app.ActivityThread.main(ActivityThread.java:3835)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at java.lang.reflect.Method.invokeNative(Native Method)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at java.lang.reflect.Method.invoke(Method.java:507)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

10-25 22:11:10.340 E/AndroidRuntime( 2551):     at dalvik.system.NativeStart.main(Native Method)

10-25 22:11:10.340 E/AndroidRuntime( 2551): Caused by: android.database.sqlite.SQLiteException: unrecognized token: "'温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】": , while compiling: SELECT _id, date, thread_id, body FROM (SELECT DISTINCT date \* 1 AS normalized_date, _id, date, thread_id, body FROM sms WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】����' AND thread_id = 1 AND (type != 3)) UNION SELECT DISTINCT date \* 1000 AS normalized_date, pdu._id, date, thread_id, NULL AS body FROM pdu LEFT JOIN pending_msgs ON pdu._id = pending_msgs.msg_id WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】����' AND thread_id = 1 AND msg_box != 3 AND (msg_box != 3 AND (m_type = 128 OR m_type = 132 OR m_type = 130))) ORDER BY date DESC) ORDER BY date 

10-25 22:11:10.360 W/ActivityManager( 1484):   Force finishing activity com.antutu.MmsExtra/.smspopup.SmsPopupActivity

**Comment by jlm346383101** [comment] 2012-11-01 19:39
Get it, this happens on other CM7 roms i've used! thanks for your reply!
 
Personally i have one thing that would be somebody of xda devs working on porting kernel from xoom for our atrix. I apologize if this question boring you!

------------------ 原始邮件 ------------------

发件人: "Michael Montuori"notifications@github.com;
发送时间: 2012年11月2日(星期五) 凌晨3:31
收件人: "mmontuori/atrix-mrom"atrix-mrom@noreply.github.com; 
抄送: "jlm346383101"346383101@qq.com; 
主题: Re: [atrix-mrom] MmsExtra process FC when screen is lighten up by mms ONLY from China Unicom！ (#19)

This appears to be an application issue, mmsextra gets the following exception, forward this to antutu MmsExtra application developer:
10-25 22:11:10.340 E/AndroidRuntime( 2551): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.antutu.MmsExtra/com.antutu.MmsExtra.smspopup.SmsPopupActivity}: android.database.sqlite.SQLiteException: unrecognized token: "'温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】": , while compiling: SELECT _id, date, thread_id, body FROM (SELECT DISTINCT date \* 1 AS normalized_date, _id, date, thread_id, body FROM sms WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】 ' AND thread_id = 1 AND (type != 3)) UNION SELECT DISTINCT date \* 1000 AS normalized_date, pdu._id, date, thread_id, NULL AS body FROM pdu LEFT JOIN pending_msgs ON pdu._id = pending_msgs.msg_id WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】 ' AND thread_id = 1 AND msg_box != 3 AND (msg_box != 3 AND (m_type = 128 OR m_type = 132 OR m_type = 130))) ORDER BY date DESC) ORDER BY date DESC
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.app.ActivityThread.access$1500(ActivityThread.java:123)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.os.Handler.dispatchMessage(Handler.java:99)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.os.Looper.loop(Looper.java:130)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at android.app.ActivityThread.main(ActivityThread.java:3835)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at java.lang.reflect.Method.invokeNative(Native Method)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at java.lang.reflect.Method.invoke(Method.java:507)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
10-25 22:11:10.340 E/AndroidRuntime( 2551): at dalvik.system.NativeStart.main(Native Method)
10-25 22:11:10.340 E/AndroidRuntime( 2551): Caused by: android.database.sqlite.SQLiteException: unrecognized token: "'温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】": , while compiling: SELECT _id, date, thread_id, body FROM (SELECT DISTINCT date \* 1 AS normalized_date, _id, date, thread_id, body FROM sms WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】 ' AND thread_id = 1 AND (type != 3)) UNION SELECT DISTINCT date \* 1000 AS normalized_date, pdu._id, date, thread_id, NULL AS body FROM pdu LEFT JOIN pending_msgs ON pdu._id = pending_msgs.msg_id WHERE (body = '温馨提示：截止到2012年10月24日，您当月套餐内流量已使用212.17MB，剩余流量87.83MB（如您订购了红围脖或云雀流量叠加包，则该包内的剩余流量包含在剩余总流量内，请注意区分使用）。本次查询结果存在延时，请以出账为准。【买3G就上 10010.com】 ' AND thread_id = 1 AND msg_box != 3 AND (msg_box != 3 AND (m_type = 128 OR m_type = 132 OR m_type = 130))) ORDER BY date DESC) ORDER BY date 
10-25 22:11:10.360 W/ActivityManager( 1484): Force finishing activity com.antutu.MmsExtra/.smspopup.SmsPopupActivity

**Comment by mmontuori** [comment] 2012-11-01 19:45
You have something that can help on porting the xoom kernel to atrix?

**Comment by jlm346383101** [comment] 2012-11-01 19:50
sorry that I have nothing to help you guys.
I asked you just out of my curious.
Sorry for interrupting you about this.

------------------ 原始邮件 ------------------

发件人: "Michael Montuori"notifications@github.com;
发送时间: 2012年11月2日(星期五) 凌晨3:45
收件人: "mmontuori/atrix-mrom"atrix-mrom@noreply.github.com; 
抄送: "jlm346383101"346383101@qq.com; 
主题: Re: [atrix-mrom] MmsExtra process FC when screen is lighten up by mms ONLY from China Unicom！ (#19)

You have something that can help on porting the xoom kernel to atrix?

**Comment by mmontuori** [comment] 2012-11-01 20:18
no problem... thanks... closing ticket

**Closed as completed by mmontuori** 2012-11-01 20:18 UTC
